In [158]:
import numpy as np
import pandas as pd

In [159]:
df = pd.read_csv(r"C:\Users\Ibhrahim ansari\Desktop\self projects\1_Amazon_Cleaned.csv", parse_dates=["Date"])
df.head()

,Order id,Date,Status,Fulfilment,Sales channel,Ship-service-level,Style,Sku,Category,Size,Asin,Courier status,Qty,Currency,Amount,Ship-city,Ship-state,Ship-postal-code,Ship-country,B2b
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,unknown,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,False
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,unknown,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False

In [160]:
df.shape

(128975, 20)

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 20 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order id            128975 non-null  object
 1   Date                128975 non-null  datetime64[ns]
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales channel       128975 non-null  object
 5   Ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   Sku                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  Asin                128975 non-null  object
 11  Courier status      128975 non-null  object
 12  Qty                 128975 non-null  int64
 13  Currency            128975 non-null  object
 14  Amount              121180 non-null  float64
 15  Ship-city           128975 non-null  object
 16  Ship-state          128975 non-null  object
 17  Ship-postal-code    128942 non-null  float64
 18  Ship-country        128975 non-null  object
 19  B2b                 128975 non-null  bool
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(15)
memory usage: 18.8+ MB

In [162]:
df.describe()

,Date,Qty,Amount,Ship-postal-code
count,128975,128975.000000,121180.000000,128942.000000
mean,2022-05-29 05:39:02.100407040,0.904431,648.561465,463966.236509
min,2022-01-04 00:00:00,0.000000,0.000000,110001.000000
25%,2022-04-20 00:00:00,1.000000,449.000000,382421.000000
50%,2022-05-21 00:00:00,1.000000,605.000000,500033.000000
75%,2022-06-24 00:00:00,1.000000,788.000000,600024.000000
max,2022-12-06 00:00:00,15.000000,5584.000000,989898.000000
std,NaN,0.313354,281.211687,191476.764941

In [163]:
print("Total Orders:",df["Order id"].nunique())

Total Orders: 120378

In [164]:
print("Total Revenue:",df["Amount"].sum())

Total Revenue: 78592678.3

In [165]:
print("Average Amount:",df["Amount"].mean())

Average Amount: 648.5614647631622

In [166]:
print("Maximum Amount:",df["Amount"].max())

Maximum Amount: 5584.0

In [167]:
print("Minimum Amount:",df["Amount"].min())

Minimum Amount: 0.0

In [168]:
df["Status"].value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [169]:
df["Courier status"].value_counts()

Courier status
Shipped      109487
unknown        6872
Unshipped      6681
Cancelled      5935
Name: count, dtype: int64

In [170]:
df["Category"].value_counts()

Category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [171]:
df["Size"].value_counts()

Size
M       22711
L       22132
XL      20876
XXL     18096
S       17090
3XL     14816
XS      11161
6XL       738
5XL       550
4XL       427
Free      378
Name: count, dtype: int64

In [172]:
df["Fulfilment"].value_counts()

Fulfilment
Amazon      89698
Merchant    39277
Name: count, dtype: int64

In [173]:
df["Sales channel"].value_counts()

Sales channel
Amazon.in     128851
Non-Amazon       124
Name: count, dtype: int64

In [174]:
df["B2b"].value_counts()

B2b
False    128104
True        871
Name: count, dtype: int64

In [175]:
df.groupby("Ship-state")["Amount"].sum().sort_values(ascending = False)

Ship-state
MAHARASHTRA                    13335534.14
KARNATAKA                      10481114.37
TELANGANA                       6916615.65
UTTAR PRADESH                   6816642.08
TAMIL NADU                      6515650.11
DELHI                           4393522.41
KERALA                          3830227.58
WEST BENGAL                     3507880.44
ANDHRA PRADESH                  3219831.72
HARYANA                         2882092.99
GUJARAT                         2728651.82
RAJASTHAN                       1761131.16
MADHYA PRADESH                  1592382.98
BIHAR                           1415613.32
ODISHA                          1386372.39
PUNJAB                          1211666.84
ASSAM                           1018136.20
UTTARAKHAND                      974143.55
JHARKHAND                        919088.21
GOA                              637685.85
CHHATTISGARH                     570485.83
HIMACHAL PRADESH                 503364.51
JAMMU & KASHMIR                  456932.74
MANIPUR                          213981.99
CHANDIGARH                       211740.67
PUDUCHERRY                       192573.24
ANDAMAN AND NICOBAR ISLANDS      158723.62
NAGALAND                         145055.67
SIKKIM                           140828.66
MEGHALAYA                        119871.81
ARUNACHAL PRADESH                 98265.00
TRIPURA                           92548.40
DADRA AND NAGAR                   42138.92
MIZORAM                           41948.71
LADAKH                            38388.43
UNKNOWN                           18671.00
LAKSHADWEEP                        3175.29
Name: Amount, dtype: float64

In [176]:
df["Ship-state"].value_counts()

Ship-state
MAHARASHTRA                    22260
KARNATAKA                      17326
TAMIL NADU                     11483
TELANGANA                      11330
UTTAR PRADESH                  10638
DELHI                           7048
KERALA                          6585
WEST BENGAL                     5963
ANDHRA PRADESH                  5430
GUJARAT                         4489
HARYANA                         4415
RAJASTHAN                       2718
MADHYA PRADESH                  2529
ODISHA                          2139
BIHAR                           2114
PUNJAB                          1919
ASSAM                           1663
UTTARAKHAND                     1553
JHARKHAND                       1456
GOA                             1137
CHHATTISGARH                     909
HIMACHAL PRADESH                 788
JAMMU & KASHMIR                  702
PUDUCHERRY                       351
CHANDIGARH                       333
MANIPUR                          316
ANDAMAN AND NICOBAR ISLANDS      257
MEGHALAYA                        207
SIKKIM                           205
NAGALAND                         187
TRIPURA                          151
ARUNACHAL PRADESH                147
MIZORAM                           76
DADRA AND NAGAR                   70
LADAKH                            43
UNKNOWN                           34
LAKSHADWEEP                        4
Name: count, dtype: int64

In [177]:
df.groupby("Ship-city")["Amount"].sum().sort_values(ascending = False).head(10)

Ship-city
BENGALURU    7257748.80
HYDERABAD    5599822.35
MUMBAI       4293210.16
NEW DELHI    3952690.20
CHENNAI      3606917.94
PUNE         2794975.79
KOLKATA      1682046.99
GURUGRAM     1280854.78
THANE        1111506.35
LUCKNOW      1049983.10
Name: Amount, dtype: float64

In [178]:

df.groupby(df["Date"].dt.month)["Amount"].sum()

Date
1      2880866.33
2      2982101.41
3      3042310.01
4     20500095.00
5     17821991.32
6     15262409.88
7      2787150.37
8      2886262.76
9      2742205.46
10     2597647.85
11     2553751.13
12     2535886.78
Name: Amount, dtype: float64

In [179]:
df["Sku"]

0          SET389-KR-NP-S
1         JNE3781-KR-XXXL
2           JNE3371-KR-XL
3              J0341-DR-L
4         JNE3671-TU-XXXL
               ...
128970      JNE3697-KR-XL
128971     SET401-KR-NP-M
128972       J0157-DR-XXL
128973       J0012-SKD-XS
128974        J0003-SET-S
Name: Sku, Length: 128975, dtype: object

In [180]:
df.groupby("Sku")["Amount"].sum().sort_values(ascending = False).head(10)

Sku
J0230-SKD-M        527699.20
JNE3797-KR-L       524581.77
J0230-SKD-S        479937.14
JNE3797-KR-M       454290.16
JNE3797-KR-S       407302.57
JNE3797-KR-XL      332155.24
J0230-SKD-L        305616.95
JNE3797-KR-XS      303616.70
SET268-KR-NP-XL    284058.96
JNE3797-KR-XXXL    276375.80
Name: Amount, dtype: float64

In [181]:
df["Month"] = df["Date"].dt.month
df["Month_name"] = df["Date"].dt.month_name()
df["Year"] = df["Date"].dt.year

In [182]:
df

,Order id,Date,Status,Fulfilment,Sales channel,Ship-service-level,Style,Sku,Category,Size,...,Currency,Amount,Ship-city,Ship-state,Ship-postal-code,Ship-country,B2b,Month,Month_name,Year
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False,4,April,2022
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,False,4,April,2022
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True,4,April,2022
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False,4,April,2022
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False,4,April,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,406-6001380-7673107,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,False,5,May,2022
128971,402-9551604-7544318,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,False,5,May,2022
128972,407-9547469-3152358,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,False,5,May,2022
128973,402-6184140-0545956,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,...,INR,1199.00,HALOL,GUJARAT,389350.0,IN,False,5,May,2022
128974,408-7436540-8728312,2022-05-31,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,...,INR,696.00,RAIPUR,CHHATTISGARH,492014.0,IN,False,5,May,2022